export const companiesData = {
   companyId: 1,
   companyName: "DEMOinc",

   structure: {
      employeeId: 1030,
      employeeColor: "green",
      employeeName: "Stefan Suarez",
      position: "FIRE MARSHALL",
      rank: "FIRE MARSHALL",
      other: null,
      department: "Fire Marshall",
      subordinates: [
         {
            employeeId: 1013,
            employeeColor: "yellow",
            employeeName: "Amy Lindsey ",
            position: "BATTALION CHIEF",
            other: null,
            department: 1,
            subordinates: [
               {
                  employeeId: 1000,
                  employeeColor: "purple",
                  employeeName: "Fred Randolph",
                  position: "CAPTAIN",
                  other: null,
                  department: 1,
                  subordinates: [
                     {
                        employeeId: 1001,
                        employeeColor: "purple",
                        employeeName: "Nelson Cobb",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 1,
                        subordinates: [],
                     },
                     {
                        employeeId: 1009,
                        employeeColor: "green",
                        employeeName: "Olivia Perry",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 1,
                        subordinates: [],
                     },
                     {
                        employeeId: 1075,
                        employeeColor: "green",
                        employeeName: "Zayd Porter",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 1,
                        subordinates: [],
                     },
                     {
                        employeeId: 1083,
                        employeeColor: "green",
                        employeeName: "Isobel Booker",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 1,
                        subordinates: [],
                     },
                     {
                        employeeId: 1089,
                        employeeColor: "yellow",
                        employeeName: "Bilal Douglas",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 1,
                        subordinates: [],
                     },

                     {
                        employeeId: 1017,
                        employeeColor: "green",
                        employeeName: "Olivia Perry",
                        position: "DRIVER",
                        other: null,
                        department: 1,
                        subordinates: [],
                     },
                     {
                        employeeId: 1031,
                        employeeColor: "green",
                        employeeName: "Olivia Perry",
                        position: "DRIVER",
                        other: null,
                        department: 1,
                        subordinates: [],
                     },
                  ],
               },
               {
                  employeeId: 1055,
                  employeeColor: "purple",
                  employeeName: "Ammar Gillespie",
                  position: "CAPTAIN",
                  other: null,
                  department: 1,
                  subordinates: [
                     {
                        employeeId: 1023,
                        employeeColor: "yellow",
                        employeeName: "Hiba Beck",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 1,
                        subordinates: [],
                     },
                     {
                        employeeId: 1074,
                        employeeColor: "yellow",
                        employeeName: "Margaret Hudson",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 1,
                        subordinates: [],
                     },
                     {
                        employeeId: 1036,
                        employeeColor: "green",
                        employeeName: "Juanita Lane",
                        position: "DRIVER",
                        other: null,
                        department: 1,
                        subordinates: [],
                     },
                     {
                        employeeId: 1064,
                        employeeColor: "green",
                        employeeName: "Bradley Savage",
                        position: "DRIVER",
                        other: null,
                        department: 1,
                        subordinates: [],
                     },
                     {
                        employeeId: 1058,
                        employeeColor: "green",
                        employeeName: "Anastasia Acosta",
                        position: "DRIVER",
                        other: null,
                        department: 1,
                        subordinates: [],
                     },
                  ],
               },
            ],
         },
         {
            employeeId: 1069,
            employeeColor: "yellow",
            employeeName: "Donna Todd ",
            position: "BATTALION CHIEF",
            other: null,
            department: 2,
            subordinates: [
               {
                  employeeId: 1077,
                  employeeColor: "purple",
                  employeeName: "Lulu Hatfield",
                  position: "CAPTAIN",
                  other: null,
                  department: 2,
                  subordinates: [
                     {
                        employeeId: 1011,
                        employeeColor: "purple",
                        employeeName: "Cody Myers",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 2,
                        subordinates: [],
                     },
                     {
                        employeeId: 1080,
                        employeeColor: "purple",
                        employeeName: "Juliet Reed",
                        position: "DRIVER",
                        other: null,
                        department: 2,
                        subordinates: [],
                     },
                     {
                        employeeId: 1037,
                        employeeColor: "green",
                        employeeName: "Jermaine Mack",
                        position: "DRIVER",
                        other: null,
                        department: 2,
                        subordinates: [],
                     },
                     {
                        employeeId: 1056,
                        employeeColor: "green",
                        employeeName: "Linda Bentley",
                        position: "DRIVER",
                        other: null,
                        department: 2,
                        subordinates: [],
                     },
                  ],
               },
            ],
         },
         {
            employeeId: 1035,
            employeeColor: "yellow",
            employeeName: "Amy Lindsey ",
            position: "BATTALION CHIEF",
            other: null,
            department: 3,
            subordinates: [
               {
                  employeeId: 1015,
                  employeeColor: "purple",
                  employeeName: "Benedict Browning",
                  position: "CAPTAIN",
                  other: null,
                  department: 3,
                  subordinates: [
                     {
                        employeeId: 1042,
                        employeeColor: "purple",
                        employeeName: "Erika Graham",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 3,
                        subordinates: [],
                     },
                     {
                        employeeId: 1007,
                        employeeColor: "yellow",
                        employeeName: "Betsy Woods",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 3,
                        subordinates: [],
                     },
                     {
                        employeeId: 1092,
                        employeeColor: "purple",
                        employeeName: "Flora Lynch",
                        position: "DRIVER",
                        other: null,
                        department: 3,
                        subordinates: [],
                     },
                     {
                        employeeId: 1026,
                        employeeColor: "green",
                        employeeName: "Niamh Small",
                        position: "DRIVER",
                        other: null,
                        department: 3,
                        subordinates: [],
                     },
                  ],
               },
               {
                  employeeId: 1046,
                  employeeColor: "purple",
                  employeeName: "Catherine Pierce",
                  position: "CAPTAIN",
                  other: null,
                  department: 3,
                  subordinates: [
                     {
                        employeeId: 1043,
                        employeeColor: "green",
                        employeeName: "Niamh Small",
                        position: "DRIVER",
                        other: null,
                        department: 3,
                        subordinates: [],
                     },
                  ],
               },
            ],
         },
         {
            employeeId: 1020,
            employeeColor: "yellow",
            employeeName: "Khalil Gonzalez",
            position: "BATTALION CHIEF",
            other: null,
            department: 4,
            subordinates: [
               {
                  employeeId: 1025,
                  employeeColor: "purple",
                  employeeName: "Gladys Montoya",
                  position: "CAPTAIN",
                  other: null,
                  department: 4,
                  subordinates: [
                     {
                        employeeId: 1072,
                        employeeColor: "purple",
                        employeeName: "Wilma Sanchez",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 4,
                        subordinates: [],
                     },
                     {
                        employeeId: 1018,
                        employeeColor: "purple",
                        employeeName: "Athena Yang",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 4,
                        subordinates: [],
                     },
                     {
                        employeeId: 1079,
                        employeeColor: "purple",
                        employeeName: "Subhan Krueger",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 4,
                        subordinates: [],
                     },
                     {
                        employeeId: 1095,
                        employeeColor: "green",
                        employeeName: "Ayrton Morales",
                        position: "DRIVER",
                        other: null,
                        department: 4,
                        subordinates: [],
                     },
                  ],
               },
            ],
         },
      ],
   },
};