export const companiesData = {
   companyId: 1,
   companyName: "DEMOinc",

   structure: {
      employeeId: 1030,
      employeeColor: "green",
      employeeName: "Stefan Suarez",
      position: "FIRE MARSHALL",
      rank: "FIRE MARSHALL",
      other: null,
      department: "Fire Marshall",
      subordinates: [
         {
            employeeId: 1013,
            employeeColor: "yellow",
            employeeName: "Amy Lindsey ",
            position: "BATTALION CHIEF",
            other: null,
            department: 1,
            subordinates: [
               {
                  employeeId: 1055,
                  employeeColor: "purple",
                  employeeName: "Fred Randolph",
                  position: "CAPTAIN",
                  other: null,
                  department: 1,
                  subordinates: [
                     {
                        employeeId: 1001,
                        employeeColor: "purple",
                        employeeName: "Nelson Cobb",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 1,
                        subordinates: [],
                     },
                     {
                        employeeId: 1009,
                        employeeColor: "green",
                        employeeName: "Olivia Perry",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 3,
                        subordinates: [],
                     },
                     {
                        employeeId: 1017,
                        employeeColor: "green",
                        employeeName: "Olivia Perry",
                        position: "DRIVER",
                        other: null,
                        department: 3,
                        subordinates: [],
                     },
                     {
                        employeeId: 1031,
                        employeeColor: "green",
                        employeeName: "Olivia Perry",
                        position: "DRIVER",
                        other: null,
                        department: 3,
                        subordinates: [],
                     },
                     {
                        employeeId: 1075,
                        employeeColor: "green",
                        employeeName: "Olivia Perry",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 3,
                        subordinates: [],
                     },
                  ],
               },
            ],
         },
         {
            employeeId: 1069,
            employeeColor: "yellow",
            employeeName: "Donna Todd ",
            position: "BATTALION CHIEF",
            other: null,
            department: 2,
            subordinates: [
               {
                  employeeId: 1077,
                  employeeColor: "purple",
                  employeeName: "Lulu Hatfield",
                  position: "CAPTAIN",
                  other: null,
                  department: 2,
                  subordinates: [
                     {
                        employeeId: 1011,
                        employeeColor: "purple",
                        employeeName: "Cody Myers",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 2,
                        subordinates: [],
                     },
                     {
                        employeeId: 1037,
                        employeeColor: "green",
                        employeeName: "Jermaine Mack",
                        position: "DRIVER",
                        other: null,
                        department: 3,
                        subordinates: [],
                     },
                  ],
               },
            ],
         },
         {
            employeeId: 1035,
            employeeColor: "yellow",
            employeeName: "Amy Lindsey ",
            position: "BATTALION CHIEF",
            other: null,
            department: 1,
            subordinates: [
               {
                  employeeId: 3,
                  employeeColor: "purple",
                  employeeName: "Ben",
                  position: "CAPTAIN",
                  other: null,
                  department: 1,
                  subordinates: [
                     {
                        employeeId: 2,
                        employeeColor: "purple",
                        employeeName: "John",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 3,
                        subordinates: [],
                     },
                     {
                        employeeId: 4,
                        employeeColor: "green",
                        employeeName: "Cheli",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 3,
                        subordinates: [],
                     },
                  ],
               },
            ],
         },
         {
            employeeId: 1035,
            employeeColor: "yellow",
            employeeName: "Alastair Lamb",
            position: "BATTALION CHIEF",
            other: null,
            department: 3,
            subordinates: [
               {
                  employeeId: 1015,
                  employeeColor: "purple",
                  employeeName: "Jake Lin",
                  position: "CAPTAIN",
                  other: null,
                  department: 3,
                  subordinates: [
                     {
                        employeeId: 1042,
                        employeeColor: "purple",
                        employeeName: "Darius O'Neill",
                        position: "FIREFIGHTER",
                        other: null,
                        department: 3,
                        subordinates: [],
                     },
                     {
                        employeeId: 1092,
                        employeeColor: "green",
                        employeeName: "Arun Walsh",
                        position: "DRIVER",
                        other: null,
                        department: 3,
                        subordinates: [],
                     },
                  ],
               },
            ],
         },
      ],
   },
};