export const companiesData = {
  companyId: 1,
  companyName: "DEMOinc",

  structure: {
    employeeId: 1030,
    employeeColor: "green",
    employeeName: "Stefan Suarez",
    position: "FIRE MARSHALL",
    rank: "FIRE MARSHALL",
    other: null,
    department: "Fire Marshall",
    subordinates: [
      {
        employeeId: 1013,
        employeeColor: "yellow",
        employeeName: "Amy Lindsey ",
        position: "BATTALION CHIEF",
        other: null,
        department: 1,
        subordinates: [
          {
            employeeId: 1000,
            employeeColor: "purple",
            employeeName: "Fred Randolph",
            position: "CAPTAIN",
            other: null,
            department: "1A",
            subordinates: [
              {
                employeeId: 1001,
                employeeColor: "purple",
                employeeName: "Nelson Cobb",
                position: "FIREFIGHTER",
                other: null,
                department: 1,
                subordinates: [],
              },
              {
                employeeId: 1009,
                employeeColor: "green",
                employeeName: "Olivia Perry",
                position: "FIREFIGHTER",
                other: null,
                department: "1A",
                subordinates: [],
              },
              {
                employeeId: 1075,
                employeeColor: "green",
                employeeName: "Zayd Porter",
                position: "FIREFIGHTER",
                other: null,
                department: "1A",
                subordinates: [],
              },
              {
                employeeId: 1083,
                employeeColor: "green",
                employeeName: "Isobel Booker",
                position: "FIREFIGHTER",
                other: null,
                department: "1A",
                subordinates: [],
              },
              {
                employeeId: 1089,
                employeeColor: "yellow",
                employeeName: "Bilal Douglas",
                position: "FIREFIGHTER",
                other: null,
                department: "1A",
                subordinates: [],
              },

              {
                employeeId: 1017,
                employeeColor: "green",
                employeeName: "Olivia Perry",
                position: "DRIVER",
                other: null,
                department: "1A",
                subordinates: [],
              },
              {
                employeeId: 1031,
                employeeColor: "green",
                employeeName: "Olivia Perry",
                position: "DRIVER",
                other: null,
                department: "1A",
                subordinates: [],
              },
            ],
          },
          {
            employeeId: 1055,
            employeeColor: "purple",
            employeeName: "Ammar Gillespie",
            position: "CAPTAIN",
            other: null,
            department: "1B",
            subordinates: [
              {
                employeeId: 1023,
                employeeColor: "yellow",
                employeeName: "Hiba Beck",
                position: "FIREFIGHTER",
                other: null,
                department: "1B",
                subordinates: [],
              },
              {
                employeeId: 1074,
                employeeColor: "yellow",
                employeeName: "Margaret Hudson",
                position: "FIREFIGHTER",
                other: null,
                department: "1B",
                subordinates: [],
              },
              {
                employeeId: 1036,
                employeeColor: "green",
                employeeName: "Juanita Lane",
                position: "DRIVER",
                other: null,
                department: "1B",
                subordinates: [],
              },
              {
                employeeId: 1064,
                employeeColor: "green",
                employeeName: "Bradley Savage",
                position: "DRIVER",
                other: null,
                department: "1B",
                subordinates: [],
              },
              {
                employeeId: 1058,
                employeeColor: "green",
                employeeName: "Anastasia Acosta",
                position: "DRIVER",
                other: null,
                department: "1B",
                subordinates: [],
              },
            ],
          },
        ],
      },
      {
        employeeId: 1069,
        employeeColor: "yellow",
        employeeName: "Donna Todd ",
        position: "BATTALION CHIEF",
        other: null,
        department: 2,
        subordinates: [
          {
            employeeId: 1077,
            employeeColor: "purple",
            employeeName: "Lulu Hatfield",
            position: "CAPTAIN",
            other: null,
            department: "2A",
            subordinates: [
              {
                employeeId: 1011,
                employeeColor: "purple",
                employeeName: "Cody Myers",
                position: "FIREFIGHTER",
                other: null,
                department: "2A",
                subordinates: [],
              },
              {
                employeeId: 1080,
                employeeColor: "purple",
                employeeName: "Juliet Reed",
                position: "DRIVER",
                other: null,
                department: "2A",
                subordinates: [],
              },
              {
                employeeId: 1037,
                employeeColor: "green",
                employeeName: "Jermaine Mack",
                position: "DRIVER",
                other: null,
                department: "2A",
                subordinates: [],
              },
              {
                employeeId: 1056,
                employeeColor: "green",
                employeeName: "Linda Bentley",
                position: "DRIVER",
                other: null,
                department: "2A",
                subordinates: [],
              },
            ],
          },
          {
            employeeId: 1057,
            employeeColor: "purple",
            employeeName: "Celia Ayala",
            position: "CAPTAIN",
            other: null,
            department: "2B",
            subordinates: [
              {
                employeeId: 1019,
                employeeColor: "green",
                employeeName: "Alysha Stevens",
                position: "FIREFIGHTER",
                other: null,
                department: "2B",
                subordinates: [],
              },
              {
                employeeId: 1027,
                employeeColor: "green",
                employeeName: "Zachary Ho",
                position: "FIREFIGHTER",
                other: null,
                department: "2B",
                subordinates: [],
              },
              {
                employeeId: 1029,
                employeeColor: "green",
                employeeName: "Mia Copeland",
                position: "DRIVER",
                other: null,
                department: "2B",
                subordinates: [],
              },
              {
                employeeId: 1048,
                employeeColor: "green",
                employeeName: "Kurtis Nolan",
                position: "FIREFIGHTER",
                other: null,
                department: "2B",
                subordinates: [],
              },
              {
                employeeId: 1063,
                employeeColor: "green",
                employeeName: "Cerys Hoover",
                position: "FIREFIGHTER",
                other: null,
                department: "2B",
                subordinates: [],
              },
              {
                employeeId: 1068,
                employeeColor: "green",
                employeeName: "Yasir Lowery",
                position: "FIREFIGHTER",
                other: null,
                department: "2B",
                subordinates: [],
              },
              {
                employeeId: 1094,
                employeeColor: "green",
                employeeName: "Michelle Mckenzie",
                position: "FIREFIGHTER",
                other: null,
                department: "2B",
                subordinates: [],
              },
            ],
          },
        ],
      },
      {
        employeeId: 1035,
        employeeColor: "yellow",
        employeeName: "Amy Lindsey ",
        position: "BATTALION CHIEF",
        other: null,
        department: 3,
        subordinates: [
          {
            employeeId: 1015,
            employeeColor: "purple",
            employeeName: "Benedict Browning",
            position: "CAPTAIN",
            other: null,
            department: "3A",
            subordinates: [
              {
                employeeId: 1042,
                employeeColor: "purple",
                employeeName: "Erika Graham",
                position: "FIREFIGHTER",
                other: null,
                department: "3A",
                subordinates: [],
              },
              {
                employeeId: 1007,
                employeeColor: "yellow",
                employeeName: "Betsy Woods",
                position: "FIREFIGHTER",
                other: null,
                department: "3A",
                subordinates: [],
              },
              {
                employeeId: 1092,
                employeeColor: "purple",
                employeeName: "Flora Lynch",
                position: "DRIVER",
                other: null,
                department: "3A",
                subordinates: [],
              },
              {
                employeeId: 1026,
                employeeColor: "green",
                employeeName: "Niamh Small",
                position: "DRIVER",
                other: null,
                department: "3A",
                subordinates: [],
              },
            ],
          },
          {
            employeeId: 1046,
            employeeColor: "purple",
            employeeName: "Catherine Pierce",
            position: "CAPTAIN",
            other: null,
            department: "3B",
            subordinates: [
              {
                employeeId: 1043,
                employeeColor: "green",
                employeeName: "Niamh Small",
                position: "DRIVER",
                other: null,
                department: "3B",
                subordinates: [],
              },
            ],
          },
        ],
      },
      {
        employeeId: 1020,
        employeeColor: "yellow",
        employeeName: "Khalil Gonzalez",
        position: "BATTALION CHIEF",
        other: null,
        department: 4,
        subordinates: [
          {
            employeeId: 1025,
            employeeColor: "purple",
            employeeName: "Gladys Montoya",
            position: "CAPTAIN",
            other: null,
            department: "4A",
            subordinates: [
              {
                employeeId: 1072,
                employeeColor: "purple",
                employeeName: "Wilma Sanchez",
                position: "FIREFIGHTER",
                other: null,
                department: "4A",
                subordinates: [],
              },
              {
                employeeId: 1018,
                employeeColor: "purple",
                employeeName: "Athena Yang",
                position: "FIREFIGHTER",
                other: null,
                department: "4A",
                subordinates: [],
              },
              {
                employeeId: 1079,
                employeeColor: "purple",
                employeeName: "Subhan Krueger",
                position: "FIREFIGHTER",
                other: null,
                department: "4A",
                subordinates: [],
              },
              {
                employeeId: 1095,
                employeeColor: "green",
                employeeName: "Ayrton Morales",
                position: "DRIVER",
                other: null,
                department: "4A",
                subordinates: [],
              },
            ],
          },
          {
            employeeId: 1032,
            employeeColor: "purple",
            employeeName: "Priya Mullins",
            position: "CAPTAIN",
            other: null,
            department: "4B",
            subordinates: [
              {
                employeeId: 1045,
                employeeColor: "green",
                employeeName: "Adelaide Stein",
                position: "FIREFIGHTER",
                other: null,
                department: "4B",
                subordinates: [],
              },
              {
                employeeId: 1054,
                employeeColor: "purple",
                employeeName: "Hector Mata",
                position: "FIREFIGHTER",
                other: null,
                department: "4B",
                subordinates: [],
              },
              {
                employeeId: 1098,
                employeeColor: "purple",
                employeeName: "Elissa Craig",
                position: "FIREFIGHTER",
                other: null,
                department: 5,
                subordinates: [],
              },
              {
                employeeId: 1033,
                employeeColor: "purple",
                employeeName: "Nathan Sears",
                position: "DRIVER",
                other: null,
                department: "4B",
                subordinates: [],
              },
              {
                employeeId: 1076,
                employeeColor: "green",
                employeeName: "Dewi Stephenson",
                position: "DRIVER",
                other: null,
                department: "4B",
                subordinates: [],
              },
              {
                employeeId: 1087,
                employeeColor: "green",
                employeeName: "Celeste Hampton",
                position: "DRIVER",
                other: null,
                department: "4B",
                subordinates: [],
              },
            ],
          },
          {
            employeeId: 1065,
            employeeColor: "purple",
            employeeName: "Rabia Wang",
            position: "CAPTAIN",
            other: null,
            department: "4C",
            subordinates: [
              {
                employeeId: 1040,
                employeeColor: "yellow",
                employeeName: "Chris Santiago",
                position: "FIREFIGHTER",
                other: null,
                department: "4C",
                subordinates: [],
              },
              {
                employeeId: 1047,
                employeeColor: "yellow",
                employeeName: "Stephen Mitchell",
                position: "DRIVER",
                other: null,
                department: "4C",
                subordinates: [],
              },
              {
                employeeId: 1049,
                employeeColor: "yellow",
                employeeName: "Samantha Cameron",
                position: "DRIVER",
                other: null,
                department: "4C",
                subordinates: [],
              },
            ],
          },
          {
            employeeId: 1052,
            employeeColor: "purple",
            employeeName: "Nate Peterson",
            position: "CAPTAIN",
            other: null,
            department: "4C",
            subordinates: [
              {
                employeeId: 1060,
                employeeColor: "yellow",
                employeeName: "Bobby Barnett",
                position: "DRIVER",
                other: null,
                department: "4C",
                subordinates: [],
              },
              {
                employeeId: 1078,
                employeeColor: "yellow",
                employeeName: "Terence Sims",
                position: "FIREFIGHTER",
                other: null,
                department: "4C",
                subordinates: [],
              },
              {
                employeeId: 1099,
                employeeColor: "yellow",
                employeeName: "Kaiden Trujillo",
                position: "FIREFIGHTER",
                other: null,
                department: "4C",
                subordinates: [],
              },
            ],
          },
        ],
      },
      {
        employeeId: 1014,
        employeeColor: "yellow",
        employeeName: "Donald Bailey",
        position: "BATTALION CHIEF",
        other: null,
        department: "5",
        subordinates: [
          {
            employeeId: 1039,
            employeeColor: "yellow",
            employeeName: "Caleb Case",
            position: "CAPTAIN",
            other: null,
            department: "5A",
            subordinates: [
              {
                employeeId: 1051,
                employeeColor: "yellow",
                employeeName: "Caleb Case",
                position: "FIREFIGHTER",
                other: null,
                department: "5A",
                subordinates: [],
              },
              {
                employeeId: 1073,
                employeeColor: "yellow",
                employeeName: "Hamish Brennan",
                position: "FIREFIGHTER",
                other: null,
                department: "5A",
                subordinates: [],
              },
              {
                employeeId: 1097,
                employeeColor: "yellow",
                employeeName: "Millie Duran",
                position: "FIREFIGHTER",
                other: null,
                department: "5A",
                subordinates: [],
              },
            ],
          },
          {
            employeeId: 1066,
            employeeColor: "yellow",
            employeeName: "Freya Clark",
            position: "CAPTAIN",
            other: null,
            department: "5B",
            subordinates: [
              {
                employeeId: 1070,
                employeeColor: "yellow",
                employeeName: "Karl Orozco",
                position: "FIREFIGHTER",
                other: null,
                department: "5B",
                subordinates: [],
              },
              {
                employeeId: 1081,
                employeeColor: "yellow",
                employeeName: "Claire Howard",
                position: "FIREFIGHTER",
                other: null,
                department: "5B",
                subordinates: [],
              },
              {
                employeeId: 1059,
                employeeColor: "yellow",
                employeeName: "Ismail Tate",
                position: "FIREFIGHTER",
                other: null,
                department: "5B",
                subordinates: [],
              },
              {
                employeeId: 1002,
                employeeColor: "yellow",
                employeeName: "Ismail Tate",
                position: "DRIVER",
                other: null,
                department: "5B",
                subordinates: [],
              },
            ],
          },
          {
            employeeId: 1088,
            employeeColor: "yellow",
            employeeName: "Cecily Mays",
            position: "CAPTAIN",
            other: null,
            department: "5C",
            subordinates: [
              {
                employeeId: 1093,
                employeeColor: "yellow",
                employeeName: "Roy Caldwell",
                position: "FIREFIGHTER",
                other: null,
                department: "5C",
                subordinates: [],
              },
              {
                employeeId: 1041,
                employeeColor: "yellow",
                employeeName: "Martin Sanchez",
                position: "FIREFIGHTER",
                other: null,
                department: "5C",
                subordinates: [],
              },
              {
                employeeId: 1028,
                employeeColor: "yellow",
                employeeName: "Evangeline Cantu",
                position: "FIREFIGHTER",
                other: null,
                department: "5C",
                subordinates: [],
              },
            ],
          },
        ],
      },
    ],
  },
};
